// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/urfave/cli/v2"
	"os"
)

func main() {
	hlog.SetLevel(hlog.LevelDebug)
	app := cli.NewApp()
	app.Name = "quck"
	app.Usage = "A quck tool project"
	app.Version = "1.0"
	// The default separator for multiple parameters is modified to ";"
	//app.SliceFlagSeparator = ";"
	//s := "abc"
	//webFlag := cli.StringFlag{Name: "test", Usage: "web api", Destination: &s}

	// Commands
	app.Commands = []*cli.Command{
		{
			Name:  "web",
			Usage: "test ",
			Action: func(context *cli.Context) error {
				h := server.Default(
				//server.WithHostPorts("127.0.0.1:8080"),
				)
				//pprof.Register(h)
				register(h)
				h.Spin()
				return nil
			},
		},
	}
	err := app.Run(os.Args)
	if err != nil {
		hlog.Info(err)
	}

	//h := server.Default(config.Option{F: func(o *config.Options) {
	//	o.Addr = ":8808"
	//}})

}
