// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/urfave/cli/v2"
	"os"
	"quck/config"
)

func main() {
	hlog.SetLevel(hlog.LevelDebug)
	app := cli.NewApp()
	app.Name = "quck"
	app.Usage = "A quck tool project"
	app.Version = "1.0"
	// The default separator for multiple parameters is modified to ";"
	//app.SliceFlagSeparator = ";"
	//s := "abc"
	//webFlag := cli.StringFlag{Name: "test", Usage: "web api", Destination: &s}

	// Commands
	app.Commands = []*cli.Command{
		{
			Name:  "web",
			Usage: "test ",
			Action: func(context *cli.Context) error {
				f, err := os.OpenFile("./output.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
				if err != nil {
					panic(err)
				}
				defer f.Close()
				hlog.SetOutput(f)
				config.Init()
				h := server.Default(
					server.WithHostPorts(config.Config.Port),
				)
				//pprof.Register(h)
				register(h)
				h.Spin()
				return nil
			},
		},
	}
	err := app.Run(os.Args)
	if err != nil {
		hlog.Info(err)
	}

	//h := server.Default(config.Option{F: func(o *config.Options) {
	//	o.Addr = ":8808"
	//}})

}
