// Code generated by hertz generator.

package Api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createconversamethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversamethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
