// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/bytedance/gopkg/util/logger"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}

// WebHook
func WebHook(ctx context.Context, c *app.RequestContext) {
	body := c.Request.Body()
	logger.Info(string(body))
}
