// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "quck/biz/model/gpt/api"
)

// CreateConversaMethod .
// @router /api/conversation [POST]
func CreateConversaMethod(ctx context.Context, c *app.RequestContext) {
	//var err error

	resp := new(api.ConversaResp)

	c.JSON(consts.StatusOK, resp)
}

// ConversaMethod .
// @router /api/conversation [PUT]
func ConversaMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ConversaReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ConversaResp)

	c.JSON(consts.StatusOK, resp)
}
